// Generated by scripts/generate-city-pinyin.cjs. Do not edit by hand.
export const cityPinyinKeys: Readonly<Record<string, { name: string; key: string; initial: string }>> = {
  "beijing": {
    "name": "北京",
    "key": "beijing",
    "initial": "B"
  },
  "changchun": {
    "name": "长春",
    "key": "changchun",
    "initial": "C"
  },
  "changsha": {
    "name": "长沙",
    "key": "changsha",
    "initial": "C"
  },
  "chengdu": {
    "name": "成都",
    "key": "chengdu",
    "initial": "C"
  },
  "chongqing": {
    "name": "重庆",
    "key": "chongqing",
    "initial": "C"
  },
  "fuzhou": {
    "name": "福州",
    "key": "fuzhou",
    "initial": "F"
  },
  "guangzhou": {
    "name": "广州",
    "key": "guangzhou",
    "initial": "G"
  },
  "guiyang": {
    "name": "贵阳",
    "key": "guiyang",
    "initial": "G"
  },
  "haikou": {
    "name": "海口",
    "key": "haikou",
    "initial": "H"
  },
  "hangzhou": {
    "name": "杭州",
    "key": "hangzhou",
    "initial": "H"
  },
  "harbin": {
    "name": "哈尔滨",
    "key": "haerbin",
    "initial": "H"
  },
  "hefei": {
    "name": "合肥",
    "key": "hefei",
    "initial": "H"
  },
  "hohhot": {
    "name": "呼和浩特",
    "key": "huhehaote",
    "initial": "H"
  },
  "hongkong": {
    "name": "香港",
    "key": "xianggang",
    "initial": "X"
  },
  "jinan": {
    "name": "济南",
    "key": "jinan",
    "initial": "J"
  },
  "kunming": {
    "name": "昆明",
    "key": "kunming",
    "initial": "K"
  },
  "lanzhou": {
    "name": "兰州",
    "key": "lanzhou",
    "initial": "L"
  },
  "lhasa": {
    "name": "拉萨",
    "key": "lasa",
    "initial": "L"
  },
  "luoyang": {
    "name": "洛阳",
    "key": "luoyang",
    "initial": "L"
  },
  "nanchang": {
    "name": "南昌",
    "key": "nanchang",
    "initial": "N"
  },
  "nanjing": {
    "name": "南京",
    "key": "nanjing",
    "initial": "N"
  },
  "nanning": {
    "name": "南宁",
    "key": "nanning",
    "initial": "N"
  },
  "shanghai": {
    "name": "上海",
    "key": "shanghai",
    "initial": "S"
  },
  "shenyang": {
    "name": "沈阳",
    "key": "shenyang",
    "initial": "S"
  },
  "shenzhen": {
    "name": "深圳",
    "key": "shenzhen",
    "initial": "S"
  },
  "shijiazhuang": {
    "name": "石家庄",
    "key": "shijiazhuang",
    "initial": "S"
  },
  "suzhou": {
    "name": "苏州",
    "key": "suzhou",
    "initial": "S"
  },
  "taipei": {
    "name": "台北",
    "key": "taibei",
    "initial": "T"
  },
  "taiyuan": {
    "name": "太原",
    "key": "taiyuan",
    "initial": "T"
  },
  "tianjin": {
    "name": "天津",
    "key": "tianjin",
    "initial": "T"
  },
  "urumqi": {
    "name": "乌鲁木齐",
    "key": "wulumuqi",
    "initial": "W"
  },
  "wuhan": {
    "name": "武汉",
    "key": "wuhan",
    "initial": "W"
  },
  "xian": {
    "name": "西安",
    "key": "xian",
    "initial": "X"
  },
  "xining": {
    "name": "西宁",
    "key": "xining",
    "initial": "X"
  },
  "yinchuan": {
    "name": "银川",
    "key": "yinchuan",
    "initial": "Y"
  },
  "zhengzhou": {
    "name": "郑州",
    "key": "zhengzhou",
    "initial": "Z"
  }
};
