// Generated by scripts/generate-world-map.cjs from Natural Earth v5.1.2. Public domain.
export const worldPlaceData = [
  {
    "id": "ne-1159127243",
    "name": "梵蒂冈",
    "aliases": [
      "Vatican City"
    ],
    "region": "Vatican",
    "latitude": 41.903282,
    "longitude": 12.453387
  },
  {
    "id": "ne-1159146051",
    "name": "圣马力诺",
    "aliases": [
      "San Marino"
    ],
    "region": "San Marino",
    "latitude": 43.936096,
    "longitude": 12.44177
  },
  {
    "id": "ne-1159146061",
    "name": "瓦都兹",
    "aliases": [
      "Vaduz"
    ],
    "region": "Liechtenstein",
    "latitude": 47.133724,
    "longitude": 9.51667
  },
  {
    "id": "ne-1159146343",
    "name": "洛班巴",
    "aliases": [
      "Lobamba"
    ],
    "region": "eSwatini",
    "latitude": -26.466667,
    "longitude": 31.199997
  },
  {
    "id": "ne-1159146437",
    "name": "卢森堡",
    "aliases": [
      "Luxembourg"
    ],
    "region": "Luxembourg",
    "latitude": 49.61166,
    "longitude": 6.130003
  },
  {
    "id": "ne-1159149061",
    "name": "帕利基尔",
    "aliases": [
      "Palikir"
    ],
    "region": "Federated States of Micronesia",
    "latitude": 6.916644,
    "longitude": 158.149974
  },
  {
    "id": "ne-1159149063",
    "name": "马朱罗",
    "aliases": [
      "Majuro"
    ],
    "region": "Marshall Islands",
    "latitude": 7.103004,
    "longitude": 171.38
  },
  {
    "id": "ne-1159149071",
    "name": "富纳富提",
    "aliases": [
      "Funafuti"
    ],
    "region": "Tuvalu",
    "latitude": -8.516652,
    "longitude": 179.216647
  },
  {
    "id": "ne-1159149073",
    "name": "梅莱凯奥克",
    "aliases": [
      "Melekeok"
    ],
    "region": "Palau",
    "latitude": 7.487396,
    "longitude": 134.626549
  },
  {
    "id": "ne-1159149075",
    "name": "比鄂-雷楼",
    "aliases": [
      "Bir Lehlou"
    ],
    "region": "Western Sahara",
    "latitude": 26.119167,
    "longitude": -9.652522
  },
  {
    "id": "ne-1159149077",
    "name": "摩纳哥",
    "aliases": [
      "Monaco"
    ],
    "region": "Monaco",
    "latitude": 43.739646,
    "longitude": 7.406913
  },
  {
    "id": "ne-1159149079",
    "name": "南塔拉瓦",
    "aliases": [
      "Tarawa",
      "South Tarawa"
    ],
    "region": "Kiribati",
    "latitude": 1.338188,
    "longitude": 173.017571
  },
  {
    "id": "ne-1159149083",
    "name": "莫洛尼",
    "aliases": [
      "Moroni"
    ],
    "region": "Comoros",
    "latitude": -11.704158,
    "longitude": 43.240244
  },
  {
    "id": "ne-1159149089",
    "name": "安道尔城",
    "aliases": [
      "Andorra",
      "Andorra la Vella"
    ],
    "region": "Andorra",
    "latitude": 42.510753,
    "longitude": 1.526594
  },
  {
    "id": "ne-1159149307",
    "name": "西班牙港",
    "aliases": [
      "Port-of-Spain",
      "Port of Spain"
    ],
    "region": "Trinidad and Tobago",
    "latitude": 10.651997,
    "longitude": -61.517031
  },
  {
    "id": "ne-1159149385",
    "name": "吉佳利",
    "aliases": [
      "Kigali"
    ],
    "region": "Rwanda",
    "latitude": -1.951644,
    "longitude": 30.058586
  },
  {
    "id": "ne-1159149413",
    "name": "墨巴本",
    "aliases": [
      "Mbabane"
    ],
    "region": "eSwatini",
    "latitude": -26.316651,
    "longitude": 31.133335
  },
  {
    "id": "ne-1159149449",
    "name": "朱巴",
    "aliases": [
      "Juba"
    ],
    "region": "South Sudan",
    "latitude": 4.829975,
    "longitude": 31.580026
  },
  {
    "id": "ne-1159149457",
    "name": "海牙",
    "aliases": [
      "The Hague"
    ],
    "region": "Netherlands",
    "latitude": 52.080037,
    "longitude": 4.269961
  },
  {
    "id": "ne-1159149461",
    "name": "卢布尔雅那",
    "aliases": [
      "Ljubljana"
    ],
    "region": "Slovenia",
    "latitude": 46.055288,
    "longitude": 14.514969
  },
  {
    "id": "ne-1159149463",
    "name": "布拉迪斯拉发",
    "aliases": [
      "Bratislava"
    ],
    "region": "Slovakia",
    "latitude": 48.150018,
    "longitude": 17.116981
  },
  {
    "id": "ne-1159149469",
    "name": "多哈",
    "aliases": [
      "Doha"
    ],
    "region": "Qatar",
    "latitude": 25.286556,
    "longitude": 51.532968
  },
  {
    "id": "ne-1159149511",
    "name": "波德戈里察",
    "aliases": [
      "Podgorica"
    ],
    "region": "Montenegro",
    "latitude": 42.465972,
    "longitude": 19.266307
  },
  {
    "id": "ne-1159149593",
    "name": "斯里贾亚瓦德纳普拉科特",
    "aliases": [
      "Sri Jayawardenepura Kotte",
      "Sri Jawewardenepura Kotte"
    ],
    "region": "Sri Lanka",
    "latitude": 6.900004,
    "longitude": 79.949993
  },
  {
    "id": "ne-1159149605",
    "name": "碧瑶",
    "aliases": [
      "Baguio",
      "Baguio City"
    ],
    "region": "Philippines",
    "latitude": 16.429991,
    "longitude": 120.569943
  },
  {
    "id": "ne-1159149731",
    "name": "多多马",
    "aliases": [
      "Dodoma"
    ],
    "region": "Tanzania",
    "latitude": -6.183306,
    "longitude": 35.750004
  },
  {
    "id": "ne-1159149737",
    "name": "伯尔尼",
    "aliases": [
      "Bern"
    ],
    "region": "Switzerland",
    "latitude": 46.916683,
    "longitude": 7.466976
  },
  {
    "id": "ne-1159149741",
    "name": "阿尤恩",
    "aliases": [
      "Laayoune"
    ],
    "region": "Morocco",
    "latitude": 27.149982,
    "longitude": -13.200006
  },
  {
    "id": "ne-1159149757",
    "name": "普里什蒂纳",
    "aliases": [
      "Pristina"
    ],
    "region": "Kosovo",
    "latitude": 42.66671,
    "longitude": 21.165984
  },
  {
    "id": "ne-1159149847",
    "name": "罗索",
    "aliases": [
      "Roseau"
    ],
    "region": "Dominica",
    "latitude": 15.301016,
    "longitude": -61.387013
  },
  {
    "id": "ne-1159149869",
    "name": "吉布地",
    "aliases": [
      "Djibouti"
    ],
    "region": "Djibouti",
    "latitude": 11.595014,
    "longitude": 43.148002
  },
  {
    "id": "ne-1159149883",
    "name": "布城",
    "aliases": [
      "Putrajaya"
    ],
    "region": "Malaysia",
    "latitude": 2.932515,
    "longitude": 101.695037
  },
  {
    "id": "ne-1159149967",
    "name": "京都",
    "aliases": [
      "Kyoto"
    ],
    "region": "Japan",
    "latitude": 35.031938,
    "longitude": 135.748052
  },
  {
    "id": "ne-1159149997",
    "name": "班竹",
    "aliases": [
      "Banjul"
    ],
    "region": "The Gambia",
    "latitude": 13.453876,
    "longitude": -16.591701
  },
  {
    "id": "ne-1159150073",
    "name": "斯科普里",
    "aliases": [
      "Skopje"
    ],
    "region": "North Macedonia",
    "latitude": 42.000006,
    "longitude": 21.433461
  },
  {
    "id": "ne-1159150339",
    "name": "布里奇顿",
    "aliases": [
      "Bridgetown"
    ],
    "region": "Barbados",
    "latitude": 13.102003,
    "longitude": -59.616527
  },
  {
    "id": "ne-1159150345",
    "name": "波多诺伏",
    "aliases": [
      "Porto-Novo"
    ],
    "region": "Benin",
    "latitude": 6.483311,
    "longitude": 2.616626
  },
  {
    "id": "ne-1159150427",
    "name": "布琼布拉",
    "aliases": [
      "Bujumbura"
    ],
    "region": "Burundi",
    "latitude": -3.376087,
    "longitude": 29.360006
  },
  {
    "id": "ne-1159150431",
    "name": "金斯敦",
    "aliases": [
      "Kingstown"
    ],
    "region": "Saint Vincent and the Grenadines",
    "latitude": 13.155756,
    "longitude": -61.220236
  },
  {
    "id": "ne-1159150433",
    "name": "卡斯特里",
    "aliases": [
      "Castries"
    ],
    "region": "Saint Lucia",
    "latitude": 14.007875,
    "longitude": -60.992875
  },
  {
    "id": "ne-1159150435",
    "name": "巴斯特尔",
    "aliases": [
      "Basseterre"
    ],
    "region": "Saint Kitts and Nevis",
    "latitude": 17.302031,
    "longitude": -62.717009
  },
  {
    "id": "ne-1159150443",
    "name": "路易港",
    "aliases": [
      "Port Louis"
    ],
    "region": "Mauritius",
    "latitude": -20.166639,
    "longitude": 57.499994
  },
  {
    "id": "ne-1159150447",
    "name": "圣乔治",
    "aliases": [
      "Saint George's",
      "St. George's"
    ],
    "region": "Grenada",
    "latitude": 12.052633,
    "longitude": -61.741643
  },
  {
    "id": "ne-1159150451",
    "name": "麦纳麦",
    "aliases": [
      "Manama"
    ],
    "region": "Bahrain",
    "latitude": 26.236136,
    "longitude": 50.583052
  },
  {
    "id": "ne-1159150457",
    "name": "圣约翰",
    "aliases": [
      "Saint John's"
    ],
    "region": "Antigua and Barbuda",
    "latitude": 17.118036,
    "longitude": -61.850034
  },
  {
    "id": "ne-1159150469",
    "name": "蒙得维的亚",
    "aliases": [
      "Montevideo"
    ],
    "region": "Uruguay",
    "latitude": -34.905376,
    "longitude": -56.186823
  },
  {
    "id": "ne-1159150535",
    "name": "洛美",
    "aliases": [
      "Lomé",
      "Lome"
    ],
    "region": "Togo",
    "latitude": 6.133883,
    "longitude": 1.220811
  },
  {
    "id": "ne-1159150537",
    "name": "突尼斯",
    "aliases": [
      "Tunis"
    ],
    "region": "Tunisia",
    "latitude": 36.802778,
    "longitude": 10.179678
  },
  {
    "id": "ne-1159150565",
    "name": "阿布扎比",
    "aliases": [
      "Abu Dhabi"
    ],
    "region": "United Arab Emirates",
    "latitude": 24.466684,
    "longitude": 54.366593
  },
  {
    "id": "ne-1159150567",
    "name": "阿什哈巴德",
    "aliases": [
      "Ashgabat"
    ],
    "region": "Turkmenistan",
    "latitude": 37.949995,
    "longitude": 58.383299
  },
  {
    "id": "ne-1159150571",
    "name": "卢萨卡",
    "aliases": [
      "Lusaka"
    ],
    "region": "Zambia",
    "latitude": -15.414698,
    "longitude": 28.281382
  },
  {
    "id": "ne-1159150573",
    "name": "哈拉雷",
    "aliases": [
      "Harare"
    ],
    "region": "Zimbabwe",
    "latitude": -17.815844,
    "longitude": 31.042764
  },
  {
    "id": "ne-1159150577",
    "name": "帝力",
    "aliases": [
      "Dili"
    ],
    "region": "East Timor",
    "latitude": -8.559388,
    "longitude": 125.579456
  },
  {
    "id": "ne-1159150579",
    "name": "维拉港",
    "aliases": [
      "Port Vila"
    ],
    "region": "Vanuatu",
    "latitude": -17.73335,
    "longitude": 168.316641
  },
  {
    "id": "ne-1159150583",
    "name": "特古西加尔巴",
    "aliases": [
      "Tegucigalpa"
    ],
    "region": "Honduras",
    "latitude": 14.103991,
    "longitude": -87.219475
  },
  {
    "id": "ne-1159150585",
    "name": "乔治敦",
    "aliases": [
      "Georgetown"
    ],
    "region": "Guyana",
    "latitude": 6.801974,
    "longitude": -58.167029
  },
  {
    "id": "ne-1159150587",
    "name": "雷克雅未克",
    "aliases": [
      "Reykjavík",
      "Reykjavik"
    ],
    "region": "Iceland",
    "latitude": 64.143459,
    "longitude": -21.936546
  },
  {
    "id": "ne-1159150589",
    "name": "太子港",
    "aliases": [
      "Port-au-Prince"
    ],
    "region": "Haiti",
    "latitude": 18.54297,
    "longitude": -72.33798
  },
  {
    "id": "ne-1159150593",
    "name": "坎帕拉",
    "aliases": [
      "Kampala"
    ],
    "region": "Uganda",
    "latitude": 0.318605,
    "longitude": 32.581378
  },
  {
    "id": "ne-1159150597",
    "name": "帕拉马里博",
    "aliases": [
      "Paramaribo"
    ],
    "region": "Suriname",
    "latitude": 5.83503,
    "longitude": -55.167031
  },
  {
    "id": "ne-1159150605",
    "name": "尼亚美",
    "aliases": [
      "Niamey"
    ],
    "region": "Niger",
    "latitude": 13.518652,
    "longitude": 2.11471
  },
  {
    "id": "ne-1159150609",
    "name": "杜尚别",
    "aliases": [
      "Dushanbe"
    ],
    "region": "Tajikistan",
    "latitude": 38.560035,
    "longitude": 68.773879
  },
  {
    "id": "ne-1159150621",
    "name": "亚松森",
    "aliases": [
      "Asunción",
      "Asuncion"
    ],
    "region": "Paraguay",
    "latitude": -25.290671,
    "longitude": -57.625834
  },
  {
    "id": "ne-1159150623",
    "name": "馬拿瓜",
    "aliases": [
      "Managua"
    ],
    "region": "Nicaragua",
    "latitude": 12.154962,
    "longitude": -86.270437
  },
  {
    "id": "ne-1159150625",
    "name": "弗里敦",
    "aliases": [
      "Freetown"
    ],
    "region": "Sierra Leone",
    "latitude": 8.471957,
    "longitude": -13.236162
  },
  {
    "id": "ne-1159150645",
    "name": "伊斯兰堡",
    "aliases": [
      "Islamabad"
    ],
    "region": "Pakistan",
    "latitude": 33.689368,
    "longitude": 73.08063
  },
  {
    "id": "ne-1159150655",
    "name": "加德满都",
    "aliases": [
      "Kathmandu"
    ],
    "region": "Nepal",
    "latitude": 27.718638,
    "longitude": 85.314696
  },
  {
    "id": "ne-1159150659",
    "name": "布隆方丹",
    "aliases": [
      "Bloemfontein"
    ],
    "region": "South Africa",
    "latitude": -29.119994,
    "longitude": 26.229913
  },
  {
    "id": "ne-1159150661",
    "name": "比勒陀利亚",
    "aliases": [
      "Pretoria"
    ],
    "region": "South Africa",
    "latitude": -25.704975,
    "longitude": 28.227483
  },
  {
    "id": "ne-1159150663",
    "name": "莫尔兹比港",
    "aliases": [
      "Port Moresby"
    ],
    "region": "Papua New Guinea",
    "latitude": -9.464708,
    "longitude": 147.192504
  },
  {
    "id": "ne-1159150665",
    "name": "霍尼亚拉",
    "aliases": [
      "Honiara"
    ],
    "region": "Solomon Islands",
    "latitude": -9.437994,
    "longitude": 159.949766
  },
  {
    "id": "ne-1159150667",
    "name": "巴拿马城",
    "aliases": [
      "Panama City"
    ],
    "region": "Panama",
    "latitude": 8.969963,
    "longitude": -79.534983
  },
  {
    "id": "ne-1159150673",
    "name": "拉巴特",
    "aliases": [
      "Rabat"
    ],
    "region": "Morocco",
    "latitude": 34.025307,
    "longitude": -6.836408
  },
  {
    "id": "ne-1159150677",
    "name": "基希讷乌",
    "aliases": [
      "Chișinău",
      "Chisinau"
    ],
    "region": "Moldova",
    "latitude": 47.005024,
    "longitude": 28.857711
  },
  {
    "id": "ne-1159150683",
    "name": "马普托",
    "aliases": [
      "Maputo"
    ],
    "region": "Mozambique",
    "latitude": -25.953332,
    "longitude": 32.587217
  },
  {
    "id": "ne-1159150715",
    "name": "摩加迪休",
    "aliases": [
      "Mogadishu"
    ],
    "region": "Somalia",
    "latitude": 2.068627,
    "longitude": 45.364732
  },
  {
    "id": "ne-1159150717",
    "name": "马斯喀特",
    "aliases": [
      "Muscat"
    ],
    "region": "Oman",
    "latitude": 23.585179,
    "longitude": 58.378311
  },
  {
    "id": "ne-1159150719",
    "name": "科伦坡",
    "aliases": [
      "Colombo"
    ],
    "region": "Sri Lanka",
    "latitude": 6.931966,
    "longitude": 79.857751
  },
  {
    "id": "ne-1159150781",
    "name": "乌兰巴托",
    "aliases": [
      "Ulaanbaatar"
    ],
    "region": "Mongolia",
    "latitude": 47.918619,
    "longitude": 106.91467
  },
  {
    "id": "ne-1159150785",
    "name": "温得和克",
    "aliases": [
      "Windhoek"
    ],
    "region": "Namibia",
    "latitude": -22.570006,
    "longitude": 17.083546
  },
  {
    "id": "ne-1159150799",
    "name": "阿布贾",
    "aliases": [
      "Abuja"
    ],
    "region": "Nigeria",
    "latitude": 9.05462,
    "longitude": 7.489505
  },
  {
    "id": "ne-1159150803",
    "name": "比绍",
    "aliases": [
      "Bissau"
    ],
    "region": "Guinea Bissau",
    "latitude": 11.865024,
    "longitude": -15.598361
  },
  {
    "id": "ne-1159150807",
    "name": "安曼",
    "aliases": [
      "Amman"
    ],
    "region": "Jordan",
    "latitude": 31.951971,
    "longitude": 35.931354
  },
  {
    "id": "ne-1159150809",
    "name": "维尔纽斯",
    "aliases": [
      "Vilnius"
    ],
    "region": "Lithuania",
    "latitude": 54.683366,
    "longitude": 25.316635
  },
  {
    "id": "ne-1159150811",
    "name": "里加",
    "aliases": [
      "Riga"
    ],
    "region": "Latvia",
    "latitude": 56.950024,
    "longitude": 24.099965
  },
  {
    "id": "ne-1159150813",
    "name": "比什凯克",
    "aliases": [
      "Bishkek"
    ],
    "region": "Kyrgyzstan",
    "latitude": 42.875025,
    "longitude": 74.583258
  },
  {
    "id": "ne-1159150831",
    "name": "马塞卢",
    "aliases": [
      "Maseru"
    ],
    "region": "Lesotho",
    "latitude": -29.316674,
    "longitude": 27.483273
  },
  {
    "id": "ne-1159150835",
    "name": "塔那那利佛",
    "aliases": [
      "Antananarivo"
    ],
    "region": "Madagascar",
    "latitude": -18.914691,
    "longitude": 47.514678
  },
  {
    "id": "ne-1159150847",
    "name": "基多",
    "aliases": [
      "Quito"
    ],
    "region": "Ecuador",
    "latitude": -0.213042,
    "longitude": -78.501997
  },
  {
    "id": "ne-1159150849",
    "name": "圣荷西",
    "aliases": [
      "San José",
      "San Jose"
    ],
    "region": "Costa Rica",
    "latitude": 9.930371,
    "longitude": -84.078814
  },
  {
    "id": "ne-1159150853",
    "name": "圣萨尔瓦多",
    "aliases": [
      "San Salvador"
    ],
    "region": "El Salvador",
    "latitude": 13.70328,
    "longitude": -89.215576
  },
  {
    "id": "ne-1159150855",
    "name": "京斯敦",
    "aliases": [
      "Kingston"
    ],
    "region": "Jamaica",
    "latitude": 17.977077,
    "longitude": -76.767434
  },
  {
    "id": "ne-1159150863",
    "name": "恩贾梅纳",
    "aliases": [
      "N'Djamena",
      "Ndjamena"
    ],
    "region": "Chad",
    "latitude": 12.115042,
    "longitude": 15.047202
  },
  {
    "id": "ne-1159150867",
    "name": "马拉博",
    "aliases": [
      "Malabo"
    ],
    "region": "Equatorial Guinea",
    "latitude": 3.750015,
    "longitude": 8.783278
  },
  {
    "id": "ne-1159150873",
    "name": "阿斯马拉",
    "aliases": [
      "Asmara"
    ],
    "region": "Eritrea",
    "latitude": 15.333339,
    "longitude": 38.933324
  },
  {
    "id": "ne-1159150875",
    "name": "萨格勒布",
    "aliases": [
      "Zagreb"
    ],
    "region": "Croatia",
    "latitude": 45.800007,
    "longitude": 15.999995
  },
  {
    "id": "ne-1159150877",
    "name": "塔林",
    "aliases": [
      "Tallinn"
    ],
    "region": "Estonia",
    "latitude": 59.433877,
    "longitude": 24.728041
  },
  {
    "id": "ne-1159150907",
    "name": "利隆圭",
    "aliases": [
      "Lilongwe"
    ],
    "region": "Malawi",
    "latitude": -13.983295,
    "longitude": 33.783302
  },
  {
    "id": "ne-1159150909",
    "name": "瓜地馬拉",
    "aliases": [
      "Guatemala City",
      "Guatemala"
    ],
    "region": "Guatemala",
    "latitude": 14.623081,
    "longitude": -90.528911
  },
  {
    "id": "ne-1159150913",
    "name": "利伯维尔",
    "aliases": [
      "Libreville"
    ],
    "region": "Gabon",
    "latitude": 0.385389,
    "longitude": 9.457965
  },
  {
    "id": "ne-1159150917",
    "name": "苏瓦",
    "aliases": [
      "Suva"
    ],
    "region": "Fiji",
    "latitude": -18.133016,
    "longitude": 178.441707
  },
  {
    "id": "ne-1159150931",
    "name": "瓦尔帕莱索",
    "aliases": [
      "Valparaíso",
      "Valparaiso"
    ],
    "region": "Chile",
    "latitude": -33.047739,
    "longitude": -71.617026
  },
  {
    "id": "ne-1159150943",
    "name": "努瓦克肖特",
    "aliases": [
      "Nouakchott"
    ],
    "region": "Mauritania",
    "latitude": 18.086427,
    "longitude": -15.97534
  },
  {
    "id": "ne-1159150945",
    "name": "巴马科",
    "aliases": [
      "Bamako"
    ],
    "region": "Mali",
    "latitude": 12.65196,
    "longitude": -8.001985
  },
  {
    "id": "ne-1159150957",
    "name": "贝鲁特",
    "aliases": [
      "Beirut"
    ],
    "region": "Lebanon",
    "latitude": 33.873921,
    "longitude": 35.507762
  },
  {
    "id": "ne-1159150961",
    "name": "第比利斯",
    "aliases": [
      "Tbilisi"
    ],
    "region": "Georgia",
    "latitude": 41.726956,
    "longitude": 44.78885
  },
  {
    "id": "ne-1159150965",
    "name": "努尔苏丹",
    "aliases": [
      "Nur-Sultan",
      "Astana"
    ],
    "region": "Kazakhstan",
    "latitude": 51.181125,
    "longitude": 71.427774
  },
  {
    "id": "ne-1159150991",
    "name": "万象",
    "aliases": [
      "Vientiane"
    ],
    "region": "Laos",
    "latitude": 17.966693,
    "longitude": 102.59998
  },
  {
    "id": "ne-1159150993",
    "name": "布拉柴维尔",
    "aliases": [
      "Brazzaville"
    ],
    "region": "Congo (Brazzaville)",
    "latitude": -4.25724,
    "longitude": 15.282744
  },
  {
    "id": "ne-1159150997",
    "name": "科纳克里",
    "aliases": [
      "Conakry"
    ],
    "region": "Guinea",
    "latitude": 9.533469,
    "longitude": -13.682181
  },
  {
    "id": "ne-1159150999",
    "name": "亚穆苏克罗",
    "aliases": [
      "Yamoussoukro"
    ],
    "region": "Ivory Coast",
    "latitude": 6.818381,
    "longitude": -5.275503
  },
  {
    "id": "ne-1159151059",
    "name": "渥太华",
    "aliases": [
      "Ottawa"
    ],
    "region": "Canada",
    "latitude": 45.418643,
    "longitude": -75.701961
  },
  {
    "id": "ne-1159151079",
    "name": "贝尔格莱德",
    "aliases": [
      "Belgrade"
    ],
    "region": "Serbia",
    "latitude": 44.820591,
    "longitude": 20.466045
  },
  {
    "id": "ne-1159151083",
    "name": "斯里巴加湾",
    "aliases": [
      "Bandar Seri Begawan"
    ],
    "region": "Brunei",
    "latitude": 4.883331,
    "longitude": 114.933284
  },
  {
    "id": "ne-1159151095",
    "name": "苏克雷",
    "aliases": [
      "Sucre"
    ],
    "region": "Bolivia",
    "latitude": -19.040971,
    "longitude": -65.259516
  },
  {
    "id": "ne-1159151109",
    "name": "贝尔墨邦",
    "aliases": [
      "Belmopan"
    ],
    "region": "Belize",
    "latitude": 17.252033,
    "longitude": -88.767073
  },
  {
    "id": "ne-1159151111",
    "name": "班吉",
    "aliases": [
      "Bangui"
    ],
    "region": "Central African Republic",
    "latitude": 4.366644,
    "longitude": 18.558288
  },
  {
    "id": "ne-1159151115",
    "name": "雅温得",
    "aliases": [
      "Yaoundé",
      "Yaounde"
    ],
    "region": "Cameroon",
    "latitude": 3.868647,
    "longitude": 11.514705
  },
  {
    "id": "ne-1159151117",
    "name": "地拉那",
    "aliases": [
      "Tirana"
    ],
    "region": "Albania",
    "latitude": 41.327541,
    "longitude": 19.818883
  },
  {
    "id": "ne-1159151119",
    "name": "埃里温",
    "aliases": [
      "Yerevan"
    ],
    "region": "Armenia",
    "latitude": 40.183097,
    "longitude": 44.511606
  },
  {
    "id": "ne-1159151123",
    "name": "巴库",
    "aliases": [
      "Baku"
    ],
    "region": "Azerbaijan",
    "latitude": 40.397218,
    "longitude": 49.860271
  },
  {
    "id": "ne-1159151127",
    "name": "金边",
    "aliases": [
      "Phnom Penh"
    ],
    "region": "Cambodia",
    "latitude": 11.551976,
    "longitude": 104.914689
  },
  {
    "id": "ne-1159151133",
    "name": "拉巴斯",
    "aliases": [
      "La Paz"
    ],
    "region": "Bolivia",
    "latitude": -16.496028,
    "longitude": -68.151931
  },
  {
    "id": "ne-1159151141",
    "name": "科托努",
    "aliases": [
      "Cotonou"
    ],
    "region": "Benin",
    "latitude": 6.36298,
    "longitude": 2.404355
  },
  {
    "id": "ne-1159151147",
    "name": "索非亚",
    "aliases": [
      "Sofia"
    ],
    "region": "Bulgaria",
    "latitude": 42.685295,
    "longitude": 23.314708
  },
  {
    "id": "ne-1159151149",
    "name": "明斯克",
    "aliases": [
      "Minsk"
    ],
    "region": "Belarus",
    "latitude": 53.901923,
    "longitude": 27.564681
  },
  {
    "id": "ne-1159151151",
    "name": "廷布",
    "aliases": [
      "Thimphu"
    ],
    "region": "Bhutan",
    "latitude": 27.472986,
    "longitude": 89.639014
  },
  {
    "id": "ne-1159151153",
    "name": "嘉柏隆里",
    "aliases": [
      "Gaborone"
    ],
    "region": "Botswana",
    "latitude": -24.646314,
    "longitude": 25.911948
  },
  {
    "id": "ne-1159151161",
    "name": "堪培拉",
    "aliases": [
      "Canberra"
    ],
    "region": "Australia",
    "latitude": -35.283029,
    "longitude": 149.129026
  },
  {
    "id": "ne-1159151173",
    "name": "瓦加杜古",
    "aliases": [
      "Ouagadougou"
    ],
    "region": "Burkina Faso",
    "latitude": 12.372262,
    "longitude": -1.52667
  },
  {
    "id": "ne-1159151177",
    "name": "萨拉热窝",
    "aliases": [
      "Sarajevo"
    ],
    "region": "Bosnia and Herzegovina",
    "latitude": 43.850022,
    "longitude": 18.383002
  },
  {
    "id": "ne-1159151179",
    "name": "奈比多",
    "aliases": [
      "Naypyidaw"
    ],
    "region": "Myanmar",
    "latitude": 19.768503,
    "longitude": 96.116673
  },
  {
    "id": "ne-1159151187",
    "name": "努库阿洛法",
    "aliases": [
      "Nuku'alofa",
      "Nukualofa"
    ],
    "region": "Tonga",
    "latitude": -21.138512,
    "longitude": -175.220564
  },
  {
    "id": "ne-1159151189",
    "name": "哈尔格萨",
    "aliases": [
      "Hargeisa",
      "Hargeysa"
    ],
    "region": "Somaliland",
    "latitude": 9.560022,
    "longitude": 44.06531
  },
  {
    "id": "ne-1159151191",
    "name": "維多利亞",
    "aliases": [
      "Victoria"
    ],
    "region": "Seychelles",
    "latitude": -4.616632,
    "longitude": 55.44999
  },
  {
    "id": "ne-1159151195",
    "name": "圣多美",
    "aliases": [
      "São Tomé",
      "Sao Tome"
    ],
    "region": "Sao Tome and Principe",
    "latitude": 0.337466,
    "longitude": 6.72965
  },
  {
    "id": "ne-1159151197",
    "name": "阿皮亚",
    "aliases": [
      "Apia"
    ],
    "region": "Samoa",
    "latitude": -13.835715,
    "longitude": -171.768599
  },
  {
    "id": "ne-1159151199",
    "name": "瓦莱塔",
    "aliases": [
      "Valletta"
    ],
    "region": "Malta",
    "latitude": 35.899732,
    "longitude": 14.514711
  },
  {
    "id": "ne-1159151201",
    "name": "马累",
    "aliases": [
      "Malé",
      "Male"
    ],
    "region": "Maldives",
    "latitude": 4.172037,
    "longitude": 73.508901
  },
  {
    "id": "ne-1159151203",
    "name": "耶路撒冷",
    "aliases": [
      "Jerusalem"
    ],
    "region": "Israel",
    "latitude": 31.778408,
    "longitude": 35.206626
  },
  {
    "id": "ne-1159151205",
    "name": "培亞",
    "aliases": [
      "Praia"
    ],
    "region": "Cape Verde",
    "latitude": 14.916698,
    "longitude": -23.516689
  },
  {
    "id": "ne-1159151207",
    "name": "拿骚",
    "aliases": [
      "Nassau"
    ],
    "region": "The Bahamas",
    "latitude": 25.08339,
    "longitude": -77.350044
  },
  {
    "id": "ne-1159151209",
    "name": "尼科西亚",
    "aliases": [
      "Nicosia"
    ],
    "region": "Cyprus",
    "latitude": 35.166677,
    "longitude": 33.366635
  },
  {
    "id": "ne-1159151699",
    "name": "惠灵顿",
    "aliases": [
      "Wellington"
    ],
    "region": "New Zealand",
    "latitude": -41.292068,
    "longitude": 174.777201
  },
  {
    "id": "ne-1159151251",
    "name": "河内",
    "aliases": [
      "Hanoi"
    ],
    "region": "Vietnam",
    "latitude": 21.035273,
    "longitude": 105.848068
  },
  {
    "id": "ne-1159151255",
    "name": "安卡拉",
    "aliases": [
      "Ankara"
    ],
    "region": "Turkey",
    "latitude": 39.929184,
    "longitude": 32.862446
  },
  {
    "id": "ne-1159151257",
    "name": "布达佩斯",
    "aliases": [
      "Budapest"
    ],
    "region": "Hungary",
    "latitude": 47.501952,
    "longitude": 19.081375
  },
  {
    "id": "ne-1159151259",
    "name": "萨那",
    "aliases": [
      "Sanaa"
    ],
    "region": "Yemen",
    "latitude": 15.356679,
    "longitude": 44.204648
  },
  {
    "id": "ne-1159151263",
    "name": "布加勒斯特",
    "aliases": [
      "Bucharest"
    ],
    "region": "Romania",
    "latitude": 44.435318,
    "longitude": 26.098001
  },
  {
    "id": "ne-1159151269",
    "name": "大马士革",
    "aliases": [
      "Damascus"
    ],
    "region": "Syria",
    "latitude": 33.50198,
    "longitude": 36.29805
  },
  {
    "id": "ne-1159151273",
    "name": "里斯本",
    "aliases": [
      "Lisbon"
    ],
    "region": "Portugal",
    "latitude": 38.724669,
    "longitude": -9.146812
  },
  {
    "id": "ne-1159151275",
    "name": "喀土穆",
    "aliases": [
      "Khartoum"
    ],
    "region": "Sudan",
    "latitude": 15.590024,
    "longitude": 32.532233
  },
  {
    "id": "ne-1159151281",
    "name": "奥斯陆",
    "aliases": [
      "Oslo"
    ],
    "region": "Norway",
    "latitude": 59.918636,
    "longitude": 10.748033
  },
  {
    "id": "ne-1159151299",
    "name": "华沙",
    "aliases": [
      "Warsaw"
    ],
    "region": "Poland",
    "latitude": 52.230872,
    "longitude": 21.005347
  },
  {
    "id": "ne-1159151303",
    "name": "平壤",
    "aliases": [
      "Pyongyang"
    ],
    "region": "North Korea",
    "latitude": 39.021385,
    "longitude": 125.752745
  },
  {
    "id": "ne-1159151305",
    "name": "三蘭港",
    "aliases": [
      "Dar es Salaam"
    ],
    "region": "Tanzania",
    "latitude": -6.798067,
    "longitude": 39.266396
  },
  {
    "id": "ne-1159151309",
    "name": "都柏林",
    "aliases": [
      "Dublin"
    ],
    "region": "Ireland",
    "latitude": 53.346731,
    "longitude": -6.25698
  },
  {
    "id": "ne-1159151311",
    "name": "蒙罗维亚",
    "aliases": [
      "Monrovia"
    ],
    "region": "Liberia",
    "latitude": 6.314582,
    "longitude": -10.79966
  },
  {
    "id": "ne-1159151317",
    "name": "吉隆坡",
    "aliases": [
      "Kuala Lumpur"
    ],
    "region": "Malaysia",
    "latitude": 3.139797,
    "longitude": 101.688699
  },
  {
    "id": "ne-1159151347",
    "name": "哈瓦那",
    "aliases": [
      "Havana"
    ],
    "region": "Cuba",
    "latitude": 23.133905,
    "longitude": -82.366128
  },
  {
    "id": "ne-1159151359",
    "name": "布拉格",
    "aliases": [
      "Prague"
    ],
    "region": "Czechia",
    "latitude": 50.086967,
    "longitude": 14.422939
  },
  {
    "id": "ne-1159151361",
    "name": "科威特城",
    "aliases": [
      "Kuwait City"
    ],
    "region": "Kuwait",
    "latitude": 29.371664,
    "longitude": 47.976355
  },
  {
    "id": "ne-1159151401",
    "name": "圣多明哥",
    "aliases": [
      "Santo Domingo"
    ],
    "region": "Dominican Republic",
    "latitude": 18.470745,
    "longitude": -69.929742
  },
  {
    "id": "ne-1159151403",
    "name": "阿克拉",
    "aliases": [
      "Accra"
    ],
    "region": "Ghana",
    "latitude": 5.55198,
    "longitude": -0.218662
  },
  {
    "id": "ne-1159151415",
    "name": "的黎波里",
    "aliases": [
      "Tripoli"
    ],
    "region": "Libya",
    "latitude": 32.8925,
    "longitude": 13.180012
  },
  {
    "id": "ne-1159151417",
    "name": "特拉维夫",
    "aliases": [
      "Tel Aviv",
      "Tel Aviv-Yafo"
    ],
    "region": "Israel",
    "latitude": 32.081937,
    "longitude": 34.768066
  },
  {
    "id": "ne-1159151419",
    "name": "赫尔辛基",
    "aliases": [
      "Helsinki"
    ],
    "region": "Finland",
    "latitude": 60.163804,
    "longitude": 24.932457
  },
  {
    "id": "ne-1159151437",
    "name": "哥本哈根",
    "aliases": [
      "København",
      "Copenhagen",
      "Kobenhavn"
    ],
    "region": "Denmark",
    "latitude": 55.68051,
    "longitude": 12.56154
  },
  {
    "id": "ne-1159151439",
    "name": "阿比让",
    "aliases": [
      "Abidjan"
    ],
    "region": "Ivory Coast",
    "latitude": 5.323126,
    "longitude": -4.020207
  },
  {
    "id": "ne-1159151443",
    "name": "巴西利亚",
    "aliases": [
      "Brasília",
      "Brasilia"
    ],
    "region": "Brazil",
    "latitude": -15.781394,
    "longitude": -47.917998
  },
  {
    "id": "ne-1159151465",
    "name": "布鲁塞尔",
    "aliases": [
      "Brussels"
    ],
    "region": "Belgium",
    "latitude": 50.835263,
    "longitude": 4.331371
  },
  {
    "id": "ne-1159151467",
    "name": "达卡",
    "aliases": [
      "Dhaka"
    ],
    "region": "Bangladesh",
    "latitude": 23.725006,
    "longitude": 90.406634
  },
  {
    "id": "ne-1159151469",
    "name": "罗安达",
    "aliases": [
      "Luanda"
    ],
    "region": "Angola",
    "latitude": -8.83634,
    "longitude": 13.232481
  },
  {
    "id": "ne-1159151471",
    "name": "阿尔及尔",
    "aliases": [
      "Algiers"
    ],
    "region": "Algeria",
    "latitude": 36.765011,
    "longitude": 3.048607
  },
  {
    "id": "ne-1159151477",
    "name": "仰光",
    "aliases": [
      "Yangon",
      "Rangoon"
    ],
    "region": "Myanmar",
    "latitude": 16.7853,
    "longitude": 96.164732
  },
  {
    "id": "ne-1159151479",
    "name": "旧金山",
    "aliases": [
      "San Francisco"
    ],
    "region": "United States of America",
    "latitude": 37.784263,
    "longitude": -122.3996
  },
  {
    "id": "ne-1159151483",
    "name": "丹佛",
    "aliases": [
      "Denver"
    ],
    "region": "United States of America",
    "latitude": 39.741134,
    "longitude": -104.985962
  },
  {
    "id": "ne-1159151485",
    "name": "休斯敦",
    "aliases": [
      "Houston"
    ],
    "region": "United States of America",
    "latitude": 29.741273,
    "longitude": -95.348436
  },
  {
    "id": "ne-1159151487",
    "name": "迈阿密",
    "aliases": [
      "Miami"
    ],
    "region": "United States of America",
    "latitude": 25.789557,
    "longitude": -80.226052
  },
  {
    "id": "ne-1159151489",
    "name": "亚特兰大",
    "aliases": [
      "Atlanta"
    ],
    "region": "United States of America",
    "latitude": 33.739457,
    "longitude": -84.367642
  },
  {
    "id": "ne-1159151491",
    "name": "芝加哥",
    "aliases": [
      "Chicago"
    ],
    "region": "United States of America",
    "latitude": 41.847961,
    "longitude": -87.635237
  },
  {
    "id": "ne-1159151493",
    "name": "加拉加斯",
    "aliases": [
      "Caracas"
    ],
    "region": "Venezuela",
    "latitude": 10.502944,
    "longitude": -66.918983
  },
  {
    "id": "ne-1159151495",
    "name": "基辅",
    "aliases": [
      "Kyiv",
      "Kiev"
    ],
    "region": "Ukraine",
    "latitude": 50.435313,
    "longitude": 30.514682
  },
  {
    "id": "ne-1159151497",
    "name": "迪拜",
    "aliases": [
      "Dubai"
    ],
    "region": "United Arab Emirates",
    "latitude": 25.214912,
    "longitude": 55.286946
  },
  {
    "id": "ne-1159151501",
    "name": "塔什干",
    "aliases": [
      "Tashkent"
    ],
    "region": "Uzbekistan",
    "latitude": 41.303828,
    "longitude": 69.268823
  },
  {
    "id": "ne-1159151503",
    "name": "马德里",
    "aliases": [
      "Madrid"
    ],
    "region": "Spain",
    "latitude": 40.401972,
    "longitude": -3.685297
  },
  {
    "id": "ne-1159151505",
    "name": "日内瓦",
    "aliases": [
      "Geneva"
    ],
    "region": "Switzerland",
    "latitude": 46.210008,
    "longitude": 6.140028
  },
  {
    "id": "ne-1159151507",
    "name": "斯德哥尔摩",
    "aliases": [
      "Stockholm"
    ],
    "region": "Sweden",
    "latitude": 59.324127,
    "longitude": 18.0663
  },
  {
    "id": "ne-1159151509",
    "name": "曼谷",
    "aliases": [
      "Bangkok"
    ],
    "region": "Thailand",
    "latitude": 13.751945,
    "longitude": 100.514699
  },
  {
    "id": "ne-1159151511",
    "name": "利马",
    "aliases": [
      "Lima"
    ],
    "region": "Peru",
    "latitude": -12.046067,
    "longitude": -77.052008
  },
  {
    "id": "ne-1159151513",
    "name": "达喀尔",
    "aliases": [
      "Dakar"
    ],
    "region": "Senegal",
    "latitude": 14.717778,
    "longitude": -17.475076
  },
  {
    "id": "ne-1159151515",
    "name": "约翰内斯堡",
    "aliases": [
      "Johannesburg"
    ],
    "region": "South Africa",
    "latitude": -26.168099,
    "longitude": 28.028064
  },
  {
    "id": "ne-1159151519",
    "name": "阿姆斯特丹",
    "aliases": [
      "Amsterdam"
    ],
    "region": "Netherlands",
    "latitude": 52.351914,
    "longitude": 4.914694
  },
  {
    "id": "ne-1159151521",
    "name": "卡萨布兰卡",
    "aliases": [
      "Casablanca"
    ],
    "region": "Morocco",
    "latitude": 33.601922,
    "longitude": -7.618313
  },
  {
    "id": "ne-1159151523",
    "name": "首尔",
    "aliases": [
      "Seoul"
    ],
    "region": "South Korea",
    "latitude": 37.568295,
    "longitude": 126.997785
  },
  {
    "id": "ne-1159151525",
    "name": "马尼拉",
    "aliases": [
      "Manila"
    ],
    "region": "Philippines",
    "latitude": 14.606105,
    "longitude": 120.980271
  },
  {
    "id": "ne-1159151527",
    "name": "蒙特雷",
    "aliases": [
      "Monterrey"
    ],
    "region": "Mexico",
    "latitude": 25.671941,
    "longitude": -100.331931
  },
  {
    "id": "ne-1159151529",
    "name": "柏林",
    "aliases": [
      "Berlin"
    ],
    "region": "Germany",
    "latitude": 52.523764,
    "longitude": 13.399603
  },
  {
    "id": "ne-1159151531",
    "name": "乌鲁木齐",
    "aliases": [
      "Ürümqi",
      "Urumqi"
    ],
    "region": "China",
    "latitude": 43.806958,
    "longitude": 87.57306
  },
  {
    "id": "ne-1159151533",
    "name": "成都",
    "aliases": [
      "Chengdu"
    ],
    "region": "China",
    "latitude": 30.671946,
    "longitude": 104.068074
  },
  {
    "id": "ne-1159151537",
    "name": "大阪",
    "aliases": [
      "Ōsaka",
      "Osaka"
    ],
    "region": "Japan",
    "latitude": 34.691095,
    "longitude": 135.503754
  },
  {
    "id": "ne-1159151539",
    "name": "金沙萨",
    "aliases": [
      "Kinshasa"
    ],
    "region": "Congo (Kinshasa)",
    "latitude": -4.327778,
    "longitude": 15.313026
  },
  {
    "id": "ne-1159151541",
    "name": "新德里",
    "aliases": [
      "New Delhi"
    ],
    "region": "India",
    "latitude": 28.600023,
    "longitude": 77.19998
  },
  {
    "id": "ne-1159151543",
    "name": "班加罗尔",
    "aliases": [
      "Bengaluru"
    ],
    "region": "India",
    "latitude": 12.971941,
    "longitude": 77.558064
  },
  {
    "id": "ne-1159151545",
    "name": "雅典",
    "aliases": [
      "Athens"
    ],
    "region": "Greece",
    "latitude": 37.985272,
    "longitude": 23.731375
  },
  {
    "id": "ne-1159151547",
    "name": "巴格达",
    "aliases": [
      "Baghdad"
    ],
    "region": "Iraq",
    "latitude": 33.340594,
    "longitude": 44.391923
  },
  {
    "id": "ne-1159151549",
    "name": "亚的斯亚贝巴",
    "aliases": [
      "Addis Ababa"
    ],
    "region": "Ethiopia",
    "latitude": 9.035256,
    "longitude": 38.698059
  },
  {
    "id": "ne-1159151551",
    "name": "德黑兰",
    "aliases": [
      "Tehran"
    ],
    "region": "Iran",
    "latitude": 35.673889,
    "longitude": 51.422398
  },
  {
    "id": "ne-1159151555",
    "name": "温哥华",
    "aliases": [
      "Vancouver"
    ],
    "region": "Canada",
    "latitude": 49.275362,
    "longitude": -123.12359
  },
  {
    "id": "ne-1159151557",
    "name": "多伦多",
    "aliases": [
      "Toronto"
    ],
    "region": "Canada",
    "latitude": 43.664645,
    "longitude": -79.389459
  },
  {
    "id": "ne-1159151559",
    "name": "布宜诺斯艾利斯",
    "aliases": [
      "Buenos Aires"
    ],
    "region": "Argentina",
    "latitude": -34.610715,
    "longitude": -58.432513
  },
  {
    "id": "ne-1159151561",
    "name": "喀布尔",
    "aliases": [
      "Kabul"
    ],
    "region": "Afghanistan",
    "latitude": 34.518636,
    "longitude": 69.181314
  },
  {
    "id": "ne-1159151563",
    "name": "维也纳",
    "aliases": [
      "Vienna"
    ],
    "region": "Austria",
    "latitude": 48.201961,
    "longitude": 16.364693
  },
  {
    "id": "ne-1159151565",
    "name": "墨尔本",
    "aliases": [
      "Melbourne"
    ],
    "region": "Australia",
    "latitude": -37.818086,
    "longitude": 144.97307
  },
  {
    "id": "ne-1159151567",
    "name": "台北",
    "aliases": [
      "Taipei"
    ],
    "region": "Taiwan",
    "latitude": 25.035833,
    "longitude": 121.568333
  },
  {
    "id": "ne-1159151703",
    "name": "奥克兰都会区",
    "aliases": [
      "Auckland"
    ],
    "region": "New Zealand",
    "latitude": -36.848055,
    "longitude": 174.763027
  },
  {
    "id": "ne-1159151569",
    "name": "洛杉矶",
    "aliases": [
      "Los Angeles"
    ],
    "region": "United States of America",
    "latitude": 34.049219,
    "longitude": -118.231986
  },
  {
    "id": "ne-1159151573",
    "name": "华盛顿哥伦比亚特区",
    "aliases": [
      "Washington,  D.C.",
      "Washington",
      "Washington, D.C."
    ],
    "region": "United States of America",
    "latitude": 38.901495,
    "longitude": -77.011364
  },
  {
    "id": "ne-1159151575",
    "name": "纽约",
    "aliases": [
      "New York",
      "New York City"
    ],
    "region": "United States of America",
    "latitude": 40.721562,
    "longitude": -73.995718
  },
  {
    "id": "ne-1159151577",
    "name": "伦敦",
    "aliases": [
      "London"
    ],
    "region": "United Kingdom",
    "latitude": 51.501941,
    "longitude": -0.118668
  },
  {
    "id": "ne-1159151579",
    "name": "伊斯坦布尔",
    "aliases": [
      "Istanbul"
    ],
    "region": "Turkey",
    "latitude": 41.017602,
    "longitude": 28.974277
  },
  {
    "id": "ne-1159151581",
    "name": "利雅德",
    "aliases": [
      "Riyadh"
    ],
    "region": "Saudi Arabia",
    "latitude": 24.634497,
    "longitude": 46.720487
  },
  {
    "id": "ne-1159151583",
    "name": "开普敦",
    "aliases": [
      "Cape Town"
    ],
    "region": "South Africa",
    "latitude": -33.918065,
    "longitude": 18.433042
  },
  {
    "id": "ne-1159151585",
    "name": "莫斯科",
    "aliases": [
      "Moscow"
    ],
    "region": "Russia",
    "latitude": 55.75411,
    "longitude": 37.613577
  },
  {
    "id": "ne-1159151587",
    "name": "墨西哥城",
    "aliases": [
      "Mexico City"
    ],
    "region": "Mexico",
    "latitude": 19.444388,
    "longitude": -99.132934
  },
  {
    "id": "ne-1159151591",
    "name": "拉各斯",
    "aliases": [
      "Lagos"
    ],
    "region": "Nigeria",
    "latitude": 6.445208,
    "longitude": 3.389585
  },
  {
    "id": "ne-1159151593",
    "name": "罗马",
    "aliases": [
      "Rome"
    ],
    "region": "Italy",
    "latitude": 41.897902,
    "longitude": 12.481313
  },
  {
    "id": "ne-1159151595",
    "name": "北京",
    "aliases": [
      "Beijing"
    ],
    "region": "China",
    "latitude": 39.90172,
    "longitude": 116.394201
  },
  {
    "id": "ne-1159151597",
    "name": "内罗毕",
    "aliases": [
      "Nairobi"
    ],
    "region": "Kenya",
    "latitude": -1.281401,
    "longitude": 36.814711
  },
  {
    "id": "ne-1159151599",
    "name": "雅加达",
    "aliases": [
      "Jakarta"
    ],
    "region": "Indonesia",
    "latitude": -6.172472,
    "longitude": 106.827492
  },
  {
    "id": "ne-1159151601",
    "name": "波哥大",
    "aliases": [
      "Bogota",
      "Bogotá"
    ],
    "region": "Colombia",
    "latitude": 4.598369,
    "longitude": -74.08529
  },
  {
    "id": "ne-1159151603",
    "name": "开罗",
    "aliases": [
      "Cairo"
    ],
    "region": "Egypt",
    "latitude": 30.051906,
    "longitude": 31.248022
  },
  {
    "id": "ne-1159151605",
    "name": "上海",
    "aliases": [
      "Shanghai"
    ],
    "region": "China",
    "latitude": 31.218398,
    "longitude": 121.434559
  },
  {
    "id": "ne-1159151609",
    "name": "东京",
    "aliases": [
      "Tokyo"
    ],
    "region": "Japan",
    "latitude": 35.686963,
    "longitude": 139.749462
  },
  {
    "id": "ne-1159151611",
    "name": "孟买",
    "aliases": [
      "Mumbai"
    ],
    "region": "India",
    "latitude": 19.068408,
    "longitude": 72.875839
  },
  {
    "id": "ne-1159151613",
    "name": "巴黎",
    "aliases": [
      "Paris"
    ],
    "region": "France",
    "latitude": 48.858092,
    "longitude": 2.352992
  },
  {
    "id": "ne-1159151615",
    "name": "圣地亚哥",
    "aliases": [
      "Santiago"
    ],
    "region": "Chile",
    "latitude": -33.440205,
    "longitude": -70.650504
  },
  {
    "id": "ne-1159151617",
    "name": "加尔各答",
    "aliases": [
      "Kolkata"
    ],
    "region": "India",
    "latitude": 22.569579,
    "longitude": 88.369126
  },
  {
    "id": "ne-1159151619",
    "name": "里约热内卢",
    "aliases": [
      "Rio de Janeiro"
    ],
    "region": "Brazil",
    "latitude": -22.907308,
    "longitude": -43.212117
  },
  {
    "id": "ne-1159151621",
    "name": "圣保罗",
    "aliases": [
      "São Paulo",
      "Sao Paulo"
    ],
    "region": "Brazil",
    "latitude": -23.556734,
    "longitude": -46.626966
  },
  {
    "id": "ne-1159151623",
    "name": "悉尼",
    "aliases": [
      "Sydney"
    ],
    "region": "Australia",
    "latitude": -33.871373,
    "longitude": 151.212548
  },
  {
    "id": "ne-1159151627",
    "name": "新加坡",
    "aliases": [
      "Singapore"
    ],
    "region": "Singapore",
    "latitude": 1.294979,
    "longitude": 103.853875
  },
  {
    "id": "ne-1159151629",
    "name": "香港",
    "aliases": [
      "Hong Kong"
    ],
    "region": "Hong Kong S.A.R.",
    "latitude": 22.306927,
    "longitude": 114.183064
  }
] as const;
